### PR TITLE
Get-WeekdayFrom.ps1

### PR DESCRIPTION
**Pull request by aaroncalderon**
Modified script from Get-Weekday.ps1 and added parameter `-FromDate` to get the desired weekday relative to the provided date.

### CODE REVIEW

**Comment by aaroncalderon** [comment]
@adbertram can you review this PR. Why have all your issues gone away?

**Comment by adbertram** [comment]
Sorry for the delay. Looks great! I removed the Issues because I don't support these scripts. They are just random scripts I've created along the way and I never intended to provide support around them.

**Review by adbertram — APPROVED** [review]

**Comment by adbertram** [comment]
This looks like you issued a PR to your own repo. I don't see it on mine.

**Comment by aaroncalderon** [comment]
@adbertram you are right. I'm sorry. I can create a new PR and send it over to your repo if you like. 

Let me know.

**Pull request closed without merging**
